openapi: 3.0.3
info:
  version: 1.1.0
  title: Aurora Debug API
  description: "A list of the currently provided debug interfaces to interact with the aurorafs node"

security:
  - { }

externalDocs:
  description: Browse the documentation @ the aurorafs Docs
  url: ""

servers:
  - url: "http://{apiRoot}:{port}"
    variables:
      apiRoot:
        default: "localhost"
        description: Base address of the local aurorafs node debug API
      port:
        default: 1635
        description: Service port provided in aurorafs node config

paths:

  "/readiness":
    get:
      summary: Get readiness state of node
      tags:
        - Status
      responses:
        "200":
          description: Health State of node
          content:
            application/json:
              schema:
                $ref: "AuroraCommon.yaml#/components/schemas/HealthStatus"
        default:
          description: Default response

  "/health":
    get:
      summary: Get health of node
      tags:
        - Status
      responses:
        "200":
          description: Health State of node
          content:
            application/json:
              schema:
                $ref: "AuroraCommon.yaml#/components/schemas/HealthStatus"
        default:
          description: Default response

  "/pingpong/{peer-id}":
    post:
      summary: Try connection to node
      tags:
        - Connectivity
      parameters:
        - in: path
          name: peer-id
          schema:
            $ref: "AuroraCommon.yaml#/components/schemas/BosonAddress"
          required: true
          description: Boson address of peer
      responses:
        "200":
          description: Returns round trip time for given peer
          content:
            application/json:
              schema:
                $ref: "AuroraCommon.yaml#/components/schemas/RttMs"
        "400":
          $ref: "AuroraCommon.yaml#/components/responses/400"
        "404":
          $ref: "AuroraCommon.yaml#/components/responses/404"
        "500":
          $ref: "AuroraCommon.yaml#/components/responses/500"
        default:
          description: Default response

  "/route/{peer-id}":
    get:
      summary: Get route from node
      tags:
        - Routetab
      parameters:
        - in: path
          name: peer-id
          schema:
            $ref: "AuroraCommon.yaml#/components/schemas/BosonAddress"
          required: true
          description: Boson address of peer
      responses:
        "200":
          description: Returns route paths for given peer
          content:
            application/json:
              schema:
                $ref: "AuroraCommon.yaml#/components/schemas/RoutePaths"
        "400":
          $ref: "AuroraCommon.yaml#/components/responses/400"
        "404":
          $ref: "AuroraCommon.yaml#/components/responses/404"
        "500":
          $ref: "AuroraCommon.yaml#/components/responses/500"
        default:
          description: Default response
    post:
      summary: Doing findroute to node
      tags:
        - Routetab
      parameters:
        - in: path
          name: peer-id
          schema:
            $ref: "AuroraCommon.yaml#/components/schemas/BosonAddress"
          required: true
          description: Boson address of peer
      responses:
        "200":
          description: Returns route paths for given peer
          content:
            application/json:
              schema:
                $ref: "AuroraCommon.yaml#/components/schemas/RoutePaths"
        "400":
          $ref: "AuroraCommon.yaml#/components/responses/400"
        "404":
          $ref: "AuroraCommon.yaml#/components/responses/404"
        "500":
          $ref: "AuroraCommon.yaml#/components/responses/500"
        default:
          description: Default response
    delete:
      summary: Delete route to node
      tags:
        - Routetab
      parameters:
        - in: path
          name: peer-id
          schema:
            $ref: "AuroraCommon.yaml#/components/schemas/BosonAddress"
          required: true
          description: Boson address of peer
      responses:
        "200":
          description: delete route paths for given peer
          content:
            application/json:
              schema:
                $ref: "AuroraCommon.yaml#/components/schemas/Response"
        "400":
          $ref: "AuroraCommon.yaml#/components/responses/400"
        "404":
          $ref: "AuroraCommon.yaml#/components/responses/404"
        "500":
          $ref: "AuroraCommon.yaml#/components/responses/500"
        default:
          description: Default response

  "/connect/{multiAddress}":
    post:
      summary: Connect to address
      tags:
        - Connectivity
      parameters:
        - in: path
          allowReserved: true
          name: multiAddress
          schema:
            $ref: "AuroraCommon.yaml#/components/schemas/MultiAddress"
          required: true
          description: Underlay address of peer
      responses:
        "200":
          description: Returns overlay address of connected peer
          content:
            application/json:
              schema:
                $ref: "AuroraCommon.yaml#/components/schemas/Address"
        "400":
          $ref: "AuroraCommon.yaml#/components/responses/400"
        "500":
          $ref: "AuroraCommon.yaml#/components/responses/500"
        default:
          description: Default response


  "/peers":
    get:
      summary: Get a list of peers
      tags:
        - Connectivity
      responses:
        "200":
          description: Returns overlay addresses of connected peers
          content:
            application/json:
              schema:
                $ref: "AuroraCommon.yaml#/components/schemas/Peers"
        default:
          description: Default response

  "/peers/{address}":
    delete:
      summary: Remove peer
      tags:
        - Connectivity
      parameters:
        - in: path
          name: address
          schema:
            $ref: "AuroraCommon.yaml#/components/schemas/BosonAddress"
          required: true
          description: Boson address of peer
      responses:
        "200":
          description: Disconnected peer
          content:
            application/json:
              schema:
                $ref: "AuroraCommon.yaml#/components/schemas/Response"
        "400":
          $ref: "AuroraCommon.yaml#/components/responses/400"
        "500":
          $ref: "AuroraCommon.yaml#/components/responses/500"
        default:
          description: Default response

  "/chunks/{address}":
    get:
      summary: Check if chunk at address exists locally
      tags:
        - Chunk
      parameters:
        - in: path
          name: address
          schema:
            $ref: "AuroraCommon.yaml#/components/schemas/BosonAddress"
          required: true
          description: Boson address of chunk
      responses:
        "200":
          description: Chunk exists
          content:
            application/json:
              schema:
                $ref: "AuroraCommon.yaml#/components/schemas/Response"
        "400":
          $ref: "AuroraCommon.yaml#/components/responses/400"
        "404":
          $ref: "AuroraCommon.yaml#/components/responses/404"
        default:
          description: Default response
    delete:
      summary: Delete a chunk from local storage
      tags:
        - Chunk
      parameters:
        - in: path
          name: address
          schema:
            $ref: "AuroraCommon.yaml#/components/schemas/BosonAddress"
          required: true
          description: Boson address of chunk
      responses:
        "200":
          description: Chunk exists
          content:
            application/json:
              schema:
                $ref: "AuroraCommon.yaml#/components/schemas/Response"
        "400":
          $ref: "AuroraCommon.yaml#/components/responses/400"
        "404":
          $ref: "AuroraCommon.yaml#/components/responses/404"
        default:
          description: Default response

  "/chunk/discover/{address}":
    get:
      summary: Get chunk discovery nodes
      tags:
        - Chunk
      parameters:
        - in: path
          name: address
          schema:
            $ref: "AuroraCommon.yaml#/components/schemas/BosonAddress"
          required: true
          description: Boson address of chunk
      responses:
        "200":
          description: Chunk exists
          content:
            application/json:
              schema:
                $ref: "AuroraCommon.yaml#/components/schemas/ChunkResponse"
        "400":
          $ref: "AuroraCommon.yaml#/components/responses/400"
        "404":
          $ref: "AuroraCommon.yaml#/components/responses/404"
        default:
          description: Default response

  "/chunk/server/{address}":
    get:
      summary: Get chunk server nodes
      tags:
        - Chunk
      parameters:
        - in: path
          name: address
          schema:
            $ref: "AuroraCommon.yaml#/components/schemas/BosonAddress"
          required: true
          description: Boson address of chunk
      responses:
        "200":
          description: Chunk exists
          content:
            application/json:
              schema:
                $ref: "AuroraCommon.yaml#/components/schemas/ChunkResponse"
        "400":
          $ref: "AuroraCommon.yaml#/components/responses/400"
        "404":
          $ref: "AuroraCommon.yaml#/components/responses/404"
        default:
          description: Default response

  "/chunk/init/{address}":
    get:
      summary: Get chunk pyramid
      tags:
        - Chunk
      parameters:
        - in: path
          name: address
          schema:
            $ref: "AuroraCommon.yaml#/components/schemas/BosonAddress"
          required: true
          description: Boson address of chunk
      responses:
        "200":
          description: Chunk exists
          content:
            application/json:
              schema:
                $ref: "AuroraCommon.yaml#/components/schemas/ChunkInfoInitResponse"
        "400":
          $ref: "AuroraCommon.yaml#/components/responses/400"
        "404":
          $ref: "AuroraCommon.yaml#/components/responses/404"
        default:
          description: Default response
  "/topology":
    get:
      description: Get topology of known network
      tags:
        - Connectivity
      responses:
        "200":
          description: Kademlia topology of the aurorafs node
          content:
            application/json:
              schema:
                $ref: "AuroraCommon.yaml#/components/schemas/Topology"

  "/welcome-message":
    get:
      summary: Get configured P2P welcome message
      tags:
        - Connectivity
      responses:
        "200":
          description: Welcome message
          content:
            application/json:
              schema:
                $ref: "AuroraCommon.yaml#/components/schemas/WelcomeMessage"
        "500":
          $ref: "AuroraCommon.yaml#/components/responses/500"
        default:
          description: Default response
    post:
      summary: Set P2P welcome message
      tags:
        - Connectivity
      requestBody:
        content:
          application/json:
            schema:
              $ref: "AuroraCommon.yaml#/components/schemas/WelcomeMessage"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "AuroraCommon.yaml#/components/schemas/Status"
        "400":
          $ref: "AuroraCommon.yaml#/components/responses/400"
        "500":
          $ref: "AuroraCommon.yaml#/components/responses/500"
        default:
          description: Default response

  "/metrics":
    get:
      summary: Get counter
      tags:
        - metrics
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "AuroraCommon.yaml#/components/schemas/Status"
        default:
          description: Default response

  "/debug/pprof/cmdline":
    get:
      summary: Get cmdline
      tags:
        - pprof
      responses:
        "200":
          description: Ok
          headers:
            "X-Content-Type-Options":
              $ref: "AuroraCommon.yaml#/components/headers/AuroraReferenceContentType"
            "Content-Type":
              $ref: "AuroraCommon.yaml#/components/headers/AuroraReferenceContentType"
          content:
            application/json:
              schema:
                $ref: "AuroraCommon.yaml#/components/schemas/ReferenceResponse"
        default:
          description: Default response

  "/debug/pprof/profile":
    get:
      summary: Get cmdline
      tags:
        - pprof
      responses:
        "200":
          description: Ok
          headers:
            "X-Content-Type-Options":
              $ref: "AuroraCommon.yaml#/components/headers/AuroraReferenceContentType"
            "Content-Type":
              $ref: "AuroraCommon.yaml#/components/headers/AuroraReferenceContentType"
            "Content-Disposition":
              $ref: "AuroraCommon.yaml#/components/headers/AuroraReferenceContentType"
          content:
            application/json:
              schema:
                $ref: "AuroraCommon.yaml#/components/schemas/ReferenceResponse"
        default:
          description: Default response

  "/debug/pprof/symbol":
    get:
      summary: Get symbol
      tags:
        - pprof
      responses:
        "200":
          description: Ok
          headers:
            "X-Content-Type-Options":
              $ref: "AuroraCommon.yaml#/components/headers/AuroraReferenceContentType"
            "Content-Type":
              $ref: "AuroraCommon.yaml#/components/headers/AuroraReferenceContentType"
          content:
            application/json:
              schema:
                $ref: "AuroraCommon.yaml#/components/schemas/ReferenceResponse"
        default:
          description: Default response

  "/debug/pprof/trace":
    get:
      summary: Get trace
      tags:
        - pprof
      responses:
        "200":
          description: Ok
          headers:
            "X-Content-Type-Options":
              $ref: "AuroraCommon.yaml#/components/headers/AuroraReferenceContentType"
            "Content-Type":
              $ref: "AuroraCommon.yaml#/components/headers/AuroraReferenceContentType"
            "Content-Disposition":
              $ref: "AuroraCommon.yaml#/components/headers/AuroraReferenceContentType"
          content:
            application/json:
              schema:
                $ref: "AuroraCommon.yaml#/components/schemas/ReferenceResponse"
        default:
          description: Default response

  "/debug/pprof/":
    get:
      summary: Get pprof
      tags:
        - pprof
      responses:
        "200":
          description: Ok
          headers:
            "X-Content-Type-Options":
              $ref: "AuroraCommon.yaml#/components/headers/AuroraReferenceContentType"
            "Content-Type":
              $ref: "AuroraCommon.yaml#/components/headers/AuroraReferenceContentType"
          content:
            application/json:
              schema:
                $ref: "AuroraCommon.yaml#/components/schemas/ReferenceResponse"
        default:
          description: Default response

  "/debug/vars":
    get:
      summary: Get vars
      tags:
        - pprof
      responses:
        "200":
          description: Ok
          headers:
            "Content-Type":
              $ref: "AuroraCommon.yaml#/components/headers/AuroraReferenceContentType"
          content:
            application/json:
              schema:
                $ref: "AuroraCommon.yaml#/components/schemas/ReferenceResponse"
        default:
          description: Default response

  "/addresses":
    get:
      summary: Get overlay and underlay addresses of the node
      tags:
        - Connectivity
      responses:
        "200":
          description: Own node underlay and overlay addresses
          content:
            application/json:
              schema:
                $ref: "AuroraCommon.yaml#/components/schemas/Addresses"
        "500":
          $ref: "AuroraCommon.yaml#/components/responses/500"
        default:
          description: Default response
