openapi: 3.0.3

info:
  version: 1.0.8
  title: Aurora API
  description: "A list of the currently provided Interfaces to interact with the boson, implementing file operations and sending messages"

security:
  - {}

externalDocs:
  description: Browse the documentation @ the aurorafs Docs
  url: ""

servers:
  - url: "http://{apiRoot}:{port}/v1"
    variables:
      apiRoot:
        default: "localhost"
        description: Base address of the local aurorafs node main API
      port:
        default: "1633"
        description: Service port provided in aurorafs node config
  - url: "http://{apiRoot}:{port}"
    variables:
      apiRoot:
        default: "localhost"
        description: Base address of the local aurorafs node main API
      port:
        default: "1633"
        description: Service port provided in aurorafs node config

paths:
# get,post /files
  "/files":
    get:
      summary: "git file list"
      tags:
        - File
      responses:
        "200":
          description: List of tags
          content:
            application/json:
              schema:
                $ref: "AuroraCommon.yaml#/components/schemas/FileList"
        "400":
          $ref: "AuroraCommon.yaml#/components/responses/400"
        "403":
          $ref: "AuroraCommon.yaml#/components/responses/403"
        "500":
          $ref: "AuroraCommon.yaml#/components/responses/500"
        default:
          description: Default response
    post:
      summary: "Upload file"
      tags:
        - File
      parameters:
        - $ref: "AuroraCommon.yaml#/components/parameters/AuroraPinParameter"
        - $ref: "AuroraCommon.yaml#/components/parameters/AuroraEncryptParameter"
        - $ref: "AuroraCommon.yaml#/components/parameters/AuroraReferenceContentType"
      requestBody:
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        "200":
          description: Ok
          headers:
            "Aurora-tag":
              $ref: "AuroraCommon.yaml#/components/headers/AuroraTag"
            "etag":
              $ref: "AuroraCommon.yaml#/components/headers/ETag"
          content:
            application/json:
              schema:
                $ref: "AuroraCommon.yaml#/components/schemas/ReferenceResponse"
        "400":
          $ref: "AuroraCommon.yaml#/components/responses/400"
        "403":
          $ref: "AuroraCommon.yaml#/components/responses/403"
        "500":
          $ref: "AuroraCommon.yaml#/components/responses/500"
        default:
          description: Default response
# get,delete /files/{address}
  "/files/{addr}":
    get:
      summary: "Get referenced file"
      tags:
        - File
      parameters:
        - in: path
          name: address
          schema:
            $ref: "AuroraCommon.yaml#/components/schemas/AuroraReference"
          required: true
          description: Aurora address of content
        - $ref: "AuroraCommon.yaml#/components/parameters/AuroraNoneMatch"
        - $ref: "AuroraCommon.yaml#/components/parameters/AuroraContentDisposition"
        - $ref: "AuroraCommon.yaml#/components/parameters/AuroraReferenceContentType"
      responses:
        "200":
          description: Ok
          headers:
            "Content-Length":
              $ref: "AuroraCommon.yaml#/components/headers/AuroraContentLength"
            "Decompressed-Content-Length":
              $ref: "AuroraCommon.yaml#/components/headers/AuroraDecompressedLength"
            "Access-Control-Expose-Headers":
              $ref: "AuroraCommon.yaml#/components/headers/AuroraAccessHeaders"
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        "400":
          $ref: "AuroraCommon.yaml#/components/responses/400"
        "404":
          $ref: "AuroraCommon.yaml#/components/responses/404"
        "500":
          $ref: "AuroraCommon.yaml#/components/responses/500"
        default:
          description: Default response
    delete:
      summary: "Delete Tag information using Uid"
      tags:
        - File
      parameters:
        - in: path
          name: address
          schema:
            $ref: "AuroraCommon.yaml#/components/schemas/AuroraReference"
          required: true
          description: Aurora address of content
      responses:
        "200":
          description: Ok
        "204":
          $ref: "AuroraCommon.yaml#/components/responses/204"
        "400":
          $ref: "AuroraCommon.yaml#/components/responses/400"
        "403":
          $ref: "AuroraCommon.yaml#/components/responses/GatewayForbidden"
        "404":
          $ref: "AuroraCommon.yaml#/components/responses/404"
        "500":
          $ref: "AuroraCommon.yaml#/components/responses/500"
        default:
          description: Default response
# post /aurora
  "/aurora":
    post:
      summary: "Upload file group"
      tags:
        - File
      parameters:
        - $ref: "AuroraCommon.yaml#/components/parameters/AuroraPinParameter"
        - $ref: "AuroraCommon.yaml#/components/parameters/AuroraEncryptParameter"
        - $ref: "AuroraCommon.yaml#/components/parameters/AuroraReferenceContentType"
        - $ref: "AuroraCommon.yaml#/components/parameters/AuroraIndexDocument"
        - $ref: "AuroraCommon.yaml#/components/parameters/AuroraErrorDocument"
      requestBody:
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: "AuroraCommon.yaml#/components/schemas/ReferenceResponse"
        "400":
          $ref: "AuroraCommon.yaml#/components/responses/400"
        "403":
          $ref: "AuroraCommon.yaml#/components/responses/403"
        "500":
          $ref: "AuroraCommon.yaml#/components/responses/500"
        default:
          description: Default response
# delete /aurora/{address}
  "/aurora/{address}":
    delete:
      summary: "Delete file group"
      tags:
        - File
      parameters:
        - in: path
          name: address
          schema:
            $ref: "AuroraCommon.yaml#/components/schemas/AuroraReference"
          required: true
          description: Aurora address of content
      responses:
        "200":
          description: Ok
        "204":
          $ref: "AuroraCommon.yaml#/components/responses/204"
        "400":
          $ref: "AuroraCommon.yaml#/components/responses/400"
        "403":
          $ref: "AuroraCommon.yaml#/components/responses/GatewayForbidden"
        "404":
          $ref: "AuroraCommon.yaml#/components/responses/404"
        "500":
          $ref: "AuroraCommon.yaml#/components/responses/500"
        default:
          description: Default response
# get /aurora/{address}/{path}
  "/aurora/{address}/{path}":
    get:
      summary: "Get file under path"
      tags:
        - File
      parameters:
        - in: path
          name: address
          schema:
            $ref: "AuroraCommon.yaml#/components/schemas/AuroraReference"
          required: true
          description: Aurora address of content
        - in: path
          name: path
          schema:
            $ref: "AuroraCommon.yaml#/components/schemas/AuroraReference"
          required: true
          description: Path to the file in the collection.
      responses:
        "200":
          description: Ok
        "204":
          $ref: "AuroraCommon.yaml#/components/responses/204"
        "400":
          $ref: "AuroraCommon.yaml#/components/responses/400"
        "403":
          $ref: "AuroraCommon.yaml#/components/responses/GatewayForbidden"
        "404":
          $ref: "AuroraCommon.yaml#/components/responses/404"
        "500":
          $ref: "AuroraCommon.yaml#/components/responses/500"
        default:
          description: Default response
# get /manifest/{address}/{path}
  "/manifest/{address}/{path}":
    get:
      summary: "If path to a directory, show items under path. Show the content type."
      tags:
        - File
      parameters:
        - in: path
          name: address
          schema:
            $ref: "AuroraCommon.yaml#/components/schemas/AuroraReference"
          required: true
          description: Aurora address of content
        - in: path
          name: path
          schema:
            $ref: "AuroraCommon.yaml#/components/schemas/AuroraReference"
          required: true
          description: An exist path in the collection. If the path point to a directory, path must end with slash.
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: "AuroraCommon.yaml#/components/schemas/ManifestViewResponse"
        "404":
          $ref: "AuroraCommon.yaml#/components/responses/404"
        "500":
          $ref: "AuroraCommon.yaml#/components/responses/500"
        default:
          description: Default response
# post /bytes
  "/bytes":
    post:
      summary: "Upload data"
      tags:
        - Bytes
      parameters:
        #        - $ref: "AuroraCommon.yaml#/components/parameters/AuroraTagParameter"
        - $ref: "AuroraCommon.yaml#/components/parameters/AuroraPinParameter"
        - $ref: "AuroraCommon.yaml#/components/parameters/AuroraEncryptParameter"
      requestBody:
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        "200":
          description: Ok
          headers:
            "Aurora-tag":
              $ref: "AuroraCommon.yaml#/components/headers/AuroraTag"
          content:
            application/json:
              schema:
                $ref: "AuroraCommon.yaml#/components/schemas/ReferenceResponse"
        "403":
          $ref: "AuroraCommon.yaml#/components/responses/403"
        "500":
          $ref: "AuroraCommon.yaml#/components/responses/500"
        default:
          description: Default response
#  get  /bytes/{address}
  "/bytes/{reference}":
    get:
      summary: "Get referenced data"
      tags:
        - Bytes
      parameters:
        - in: path
          name: reference
          schema:
            $ref: "AuroraCommon.yaml#/components/schemas/AuroraReference"
          required: true
          description: Aurora address reference to content

      responses:
        "200":
          description: Retrieved content specified by reference
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        "404":
          $ref: "AuroraCommon.yaml#/components/responses/404"
        default:
          description: Default response
# post /chunks
  "/chunks":
    post:
      summary: "Upload Chunk"
      tags:
        - Chunk
      parameters:
        - $ref: "AuroraCommon.yaml#/components/parameters/AuroraPinParameter"

      requestBody:
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: "AuroraCommon.yaml#/components/schemas/ReferenceResponse"
        "400":
          $ref: "AuroraCommon.yaml#/components/responses/400"
        "403":
          $ref: "AuroraCommon.yaml#/components/responses/403"
        "500":
          $ref: "AuroraCommon.yaml#/components/responses/500"
        default:
          description: Default response
# get /chunks/{addr}
  "/chunks/{reference}":
    get:
      summary: "Get referenced data"
      tags:
        - Chunk
      parameters:
        - $ref: "AuroraCommon.yaml#/components/parameters/AuroraRecoveryTargetsParameter"
        - in: path
          name: addr
          schema:
            $ref: "AuroraCommon.yaml#/components/schemas/AuroraReference"
          required: true
          description: Aurora address reference to content

      responses:
        "200":
          description: Retrieved content specified by reference
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        "404":
          $ref: "AuroraCommon.yaml#/components/responses/404"
        default:
          description: Default response
  "/pin/files/{address}":
    post:
      summary: "Pin the root hash with the given reference"
      tags:
        - Pinning
      parameters:
        - in: path
          name: address
          schema:
            $ref: "AuroraCommon.yaml#/components/schemas/AuroraReference"
          required: true
          description: Aurora address of content
      responses:
        "200":
          description: Ok
        "400":
          $ref: "AuroraCommon.yaml#/components/responses/400"
        "404":
          $ref: "AuroraCommon.yaml#/components/responses/404"
        "500":
          $ref: "AuroraCommon.yaml#/components/responses/500"
        default:
          description: Default response
    delete:
      summary: "Unpin the root hash with the given reference"
      tags:
        - Pinning
      parameters:
        - in: path
          name: address
          schema:
            $ref: "AuroraCommon.yaml#/components/schemas/AuroraReference"
          required: true
          description: Aurora address of content
      responses:
        "200":
          description: Ok
        "204":
          $ref: "AuroraCommon.yaml#/components/responses/204"
        "400":
          $ref: "AuroraCommon.yaml#/components/responses/400"
        "403":
          $ref: "AuroraCommon.yaml#/components/responses/GatewayForbidden"
        "404":
          $ref: "AuroraCommon.yaml#/components/responses/404"
        "500":
          $ref: "AuroraCommon.yaml#/components/responses/500"
        default:
          description: Default response
# get,delete /pin/aurora/{address}
  "/pin/aurora/{address}":
    post:
      summary: "Pin the root hash with the given reference"
      tags:
        - Pinning
      parameters:
        - in: path
          name: address
          schema:
            $ref: "AuroraCommon.yaml#/components/schemas/AuroraReference"
          required: true
          description: Aurora address of chunk
      responses:
        "200":
          description: Ok
        "400":
          $ref: "AuroraCommon.yaml#/components/responses/400"
        "404":
          $ref: "AuroraCommon.yaml#/components/responses/404"
        "500":
          $ref: "AuroraCommon.yaml#/components/responses/500"
        default:
          description: Default response
    delete:
      summary: "Unpin the root hash with the given reference"
      tags:
        - Pinning
      parameters:
        - in: path
          name: address
          schema:
            $ref: "AuroraCommon.yaml#/components/schemas/AuroraReference"
          required: true
          description: Aurora address of content
      responses:
        "200":
          description: Ok
        "204":
          $ref: "AuroraCommon.yaml#/components/responses/204"
        "400":
          $ref: "AuroraCommon.yaml#/components/responses/400"
        "403":
          $ref: "AuroraCommon.yaml#/components/responses/GatewayForbidden"
        "404":
          $ref: "AuroraCommon.yaml#/components/responses/404"
        "500":
          $ref: "AuroraCommon.yaml#/components/responses/500"
        default:
          description: Default response