openapi: 3.0.3
info:
  version: 1.0.0
  title: Common Data Types
  description: |

externalDocs:
  description: Browse the documentation @ the aurorafs Docs
  url: ""

paths: {}
components:
  schemas:
    Address:
      type: object
      properties:
        address:
          $ref: "#/components/schemas/AuroraAddress"

    BzzTopology:
      type: object
      properties:
        baseAddr:
          $ref: "#/components/schemas/AuroraAddress"
        population:
          type: integer
        connected:
          type: integer
        timestamp:
          type: string
        nnLowWatermark:
          type: integer
        depth:
          type: integer
        bins:
          type: object
          additionalProperties:
            type: object
            properties:
              population:
                type: integer
              connected:
                type: integer
              disconnectedPeers:
                type: object
              connectedPeers:
                type: object

    DateTime:
      type: string
      format: date-time
      #pattern: '^(\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{7}\+\d{2}:\d{2})$'
      example: "2020-06-11T11:26:42.6969797+02:00"

    Duration:
      description: Go time.Duration format
      type: string
      example: "5.0018ms"

    FileName:
      type: string

    Hash:
      type: object
      properties:
        hash:
          $ref: "#/components/schemas/AuroraAddress"

    BitVector:
      type: object
      properties:
        len:
          type: integer
        b:
          type: string

    NewFileResponse:
      type: object
      properties:
        fileHash:
          $ref: "#/components/schemas/Hash"
        size:
          type: integer
        pinState:
          type: boolean
        bitVector:
          $ref: "#/components/schemas/BitVector"

    FileList:
      type: object
      properties:
        tags:
          type: array
          nullable: true
          items:
            $ref: "#/components/schemas/NewFileResponse"

    HexString:
      type: string
      pattern: "^([A-Fa-f0-9]+)$"
      example: "cf880b8eeac5093fa27b0825906c600685"

    LinkAddress:
      type: string
      pattern: "^[A-Fa-f0-9]{40}$"
      example: "36b7efd913ca4cf880b8eeac5093fa27b0825906"

    MultiAddress:
      type: string

    P2PUnderlay:
      type: string
      example: "/ip4/127.0.0.1/tcp/1634/p2p/16Uiu2HAmTm17toLDaPYzRyjKn27iCB76yjKnJ5DjQXneFmifFvaX"

    Peers:
      type: object
      properties:
        peers:
          type: array
          items:
            $ref: "#/components/schemas/Address"

    PinningState:
      type: object
      properties:
        address:
          $ref: "#/components/schemas/AuroraAddress"
        pinCounter:
          type: integer

    ProblemDetails:
      type: string

    Reference:
      description: File RootCid
      type: string
      example: "4e071970bf456afc85c67889f4ce877ac31f2b317653c93e27d837b98dc3f2ac"

    ReferenceResponse:
      type: object
      properties:
        reference:
          $ref: "#/components/schemas/Reference"

    AuroraReference:
      oneOf:
        - $ref: "#/components/schemas/AuroraAddress"
        - $ref: "#/components/schemas/AuroraEncryptedReference"
        - $ref: "#/components/schemas/DomainName"

    ManifestStructure:
      type: object
      properties:
        type:
          type: string
        hash:
          $ref: "#/components/schemas/Hash"
        sub:
          $ref: "#/components/schemas/ManifestStructure"

    FileInfo:
      type: object
      properties:
        size:
          type: integer
        ext:
          type: string
        mime:
          type: string

    ManifestViewResponse:
      oneOf:
        - $ref: "#/components/schemas/ManifestStructure"
        - $ref: "#/components/schemas/FileInfo"

    Response:
      type: object
      properties:
        message:
          type: string
        code:
          type: integer

    RttMs:
      type: object
      properties:
        rtt:
          $ref: "#/components/schemas/Duration"

    Status:
      type: object
      properties:
        status:
          type: string

    AuroraAddress:
      type: string
      pattern: "^[A-Fa-f0-9]{64}$"
      example: "36b7efd913ca4cf880b8eeac5093fa27b0825906c600685b6abdd6566e6cfe8f"

    AuroraEncryptedReference:
      type: string
      pattern: "^[A-Fa-f0-9]{128}$"
      example: "36b7efd913ca4cf880b8eeac5093fa27b0825906c600685b6abdd6566e6cfe8f2d2810619d29b5dbefd5d74abce25d58b81b251baddb9c3871cf0d6967deaae2"

    DomainName:
      type: string
      pattern: '^[A-Za-z0-9]+\.[A-Za-z0-9]+$'
      example: "boson.eth"

    Uid:
      type: integer

    WelcomeMessage:
      type: object
      properties:
        welcome_message:
          type: string

  headers:
    AuroraTag:
      description: "Tag UID"
      schema:
        $ref: "AuroraCommon.yaml#/components/schemas/Uid"
    AuroraNoneMatch:
      description: "If-None-Match Batch file operation"
      schema:
        $ref: "AuroraCommon.yaml#/components/schemas/Uid"
    AuroraContentLength:
      description: "length"
      schema:
        $ref: "AuroraCommon.yaml#/components/schemas/Uid"
    AuroraDecompressedLength:
      description: "length"
      schema:
        $ref: "AuroraCommon.yaml#/components/schemas/Uid"
    AuroraAccessHeaders:
      description: "headers"
      schema:
        $ref: "AuroraCommon.yaml#/components/schemas/Uid"
    AuroraIndexDocument:
      description: "Boson-Index-Document"
      schema:
        $ref: "AuroraCommon.yaml#/components/schemas/Uid"
    AuroraErrorDocument:
      description: "Boson-Error-Document"
      schema:
        $ref: "AuroraCommon.yaml#/components/schemas/Uid"

    ETag:
      description: |
        The RFC7232 ETag header field in a response provides the current entity-
        tag for the selected resource. An entity-tag is an opaque identifier for
        different versions of a resource over time, regardless whether multiple
        versions are valid at the same time. An entity-tag consists of an opaque
        quoted string, possibly prefixed by a weakness indicator.
      schema:
        type: string

  parameters:
    AuroraPinParameter:
      in: header
      name: boson-pin
      schema:
        type: boolean
      required: false
      description: >
        Represents if the uploaded data should be also locally pinned on the node.
        Warning! Not available for nodes that run in Gateway mode!

    AuroraEncryptParameter:
      in: header
      name: boson-encrypt
      schema:
        type: boolean
      required: false
      description: Represents the encrypting state of the file

    AuroraReferenceContentType:
      in: header
      name: content-type
      schema:
        type: string
      description: The specified content-type is preserved for download of the asset

    AuroraNoneMatch:
      in: header
      name: if-none-match
      schema:
        type: string
      description: This is to specify whether to upload files in batches

    AuroraContentDisposition:
      in: header
      name: content-disposition
      schema:
        type: string
      description: This is content-disposition

    AuroraContentLength:
      in: header
      name: content-length
      schema:
        type: string
      description: This is content-length

    AuroraDecompressedLength:
      in: header
      name: decompressed-content-length
      schema:
        type: string
      description: This is decompressed-content-length

    AuroraAccessHeaders:
      in: header
      name: access-control-expose-headers
      schema:
        type: string
      description: This is access-control-expose-headers

    AuroraIndexDocument:
      in: header
      name: boson-index-document
      schema:
        type: string
      description: This is boson-index-document

    AuroraErrorDocument:
      in: header
      name: boson-error-document
      schema:
        type: string
      description: This is boson-error-document

    AuroraRecoveryTargetsParameter:
      in: query
      name: targets
      schema:
        type: string
      required: false
      description: Global pinning targets prefix

    GasPriceParameter:
      in: header
      name: gas-price
      schema:
        $ref: "AuroraCommon.yaml#/components/schemas/GasPrice"
      required: false
      description: "Gas price for transaction"

    GasLimitParameter:
      in: header
      name: gas-limit
      schema:
        $ref: "AuroraCommon.yaml#/components/schemas/GasLimit"
      required: false
      description: "Gas limit for transaction"

  responses:
    "204":
      description: The resource was deleted successfully.
    "400":
      description: Bad request
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/ProblemDetails"
    "401":
      description: Unauthorized
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/ProblemDetails"
    "403":
      description: Forbidden
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/ProblemDetails"
    "404":
      description: Not Found
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/ProblemDetails"
    "500":
      description: Internal Server Error
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/ProblemDetails"
    "GatewayForbidden":
      description: "Endpoint or header (pinning or encryption headers) forbidden in Gateway mode"
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/ProblemDetails"