version: "3"

services:
  aurora-1:
    image: gauss-project/aurora:beta
    restart: unless-stopped
    environment:
      - AURORA_API_ADDR
      - AURORA_BOOTNODE
      - AURORA_BOOTNODE_MODE
      - AURORA_CLEF_SIGNER_ENABLE
      - AURORA_CLEF_SIGNER_ENDPOINT=http://clef-1:8550
      - AURORA_CONFIG
      - AURORA_CORS_ALLOWED_ORIGINS
      - AURORA_DATA_DIR
      - AURORA_CACHE_CAPACITY
      - AURORA_DB_OPEN_FILES_LIMIT
      - AURORA_DB_BLOCK_CACHE_CAPACITY
      - AURORA_DB_WRITE_BUFFER_SIZE
      - AURORA_DB_DISABLE_SEEKS_COMPACTION
      - AURORA_DEBUG_API_ADDR
      - AURORA_DEBUG_API_ENABLE
      - AURORA_GATEWAY_MODE
      - AURORA_GLOBAL_PINNING_ENABLE
      - AURORA_NAT_ADDR
      - AURORA_NETWORK_ID
      - AURORA_P2P_ADDR
      - AURORA_P2P_QUIC_ENABLE
      - AURORA_P2P_WS_ENABLE
      - AURORA_PASSWORD
      - AURORA_PASSWORD_FILE
      - AURORA_PAYMENT_EARLY
      - AURORA_PAYMENT_THRESHOLD
      - AURORA_PAYMENT_TOLERANCE
      - AURORA_RESOLVER_OPTIONS
      - AURORA_STANDALONE
      - AURORA_SWAP_ENABLE
      - AURORA_SWAP_ENDPOINT
      - AURORA_SWAP_FACTORY_ADDRESS
      - AURORA_SWAP_INITIAL_DEPOSIT
      - AURORA_TRACING_ENABLE
      - AURORA_TRACING_ENDPOINT
      - AURORA_TRACING_SERVICE_NAME
      - AURORA_VERBOSITY
      - AURORA_WELCOME_MESSAGE
    ports:
      - "${API_ADDR:-1633}${AURORA_API_ADDR:-:1633}"
      - "${P2P_ADDR:-1634}${AURORA_P2P_ADDR:-:1634}"
      - "${DEBUG_API_ADDR:-127.0.0.1:1635}${AURORA_DEBUG_API_ADDR:-:1635}"
    volumes:
      - aurora-data:/home/aurora/.aurora
    command: start
volumes:
  aurora-data:
