#!/bin/sh -e

if [ -d /run/systemd/system ] ; then
    systemctl --system daemon-reload >/dev/null || true
fi
if [ "$1" = "remove" ]; then
    if [ -x "/usr/bin/deb-systemd-helper" ]; then
        deb-systemd-helper mask aufs.service >/dev/null
    fi
fi
if [ "$1" = "purge" ]; then
    if [ -x "/usr/bin/deb-systemd-helper" ]; then
        deb-systemd-helper purge aufs.service >/dev/null
        deb-systemd-helper unmask aufs.service >/dev/null
    fi
    userdel -r aufs >/dev/null 2>&1 || true
fi


if [ "$1" = "purge" -a -e /usr/share/debconf/confmodule ]; then
    . /usr/share/debconf/confmodule
    db_purge
fi